server:
  port: 8002
  
spring:
  application:
    name: FAULT-REPORTING-SERVICE
  datasource:
    username: root
    password: Raj
    url: jdbc:mysql://localhost:3306/stage3?useSSL=false&createDatabaseIfNotExist=true
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true

