server:
  port: 8009

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
     
      - id: FAULT-REPORTING-SERVICE
        uri: lb://FAULT-REPORTING-SERVICE
        predicates:
        - Path=/faultReporting/**
     
      - id: FAULT-ASSIGNMENT-SERVICE
        uri: lb://FAULT-ASSIGNMENT-SERVICE
        predicates:
        - Path=/faultAssignment/**
      
      - id: AGENT-SERVICE
        uri: lb://AGENT-SERVICE
        predicates:
        - Path=/agent/**
     
      
