spring:
    application:
        name: AUTH-SERVICE
    data:
        rest:
            basePath: /api/fault-reporting
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        username: root
        password: examly
        url: jdbc:mysql://localhost:3306/stage3?useSSL=false&createDatabaseIfNotExist=true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
server:
    port: 8091
jwt:
    secret: lkasjdklajsdlkjasldkjasjdlkj