spring:
    application:
        name: fault-reporting-service
    data:
        rest:
            basePath: /api/fault-reporting
    jpa:
        hibernate:
            ddl-auto: none
    datasource:
        url: jdbc:mysql://localhost/faultReporting?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
        username: root
        password: examly
server:
    port: 8082
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka/
